Feat/matching tests and ci
CS3219-AY2223S1/cs3219-project-ay2223s1-g59 pull request #30
Opened 2022-09-28 11:18 UTC by TheSpaceCuber

2022-10-01 16:27 UTC, Herrekt commented
https://stackoverflow.com/questions/28525571/how-to-add-a-delay-before-starting-a-mocha-test-case

Can add hooks that run some delays for test cases that may need to run down the full timer

2022-10-01 17:07 UTC, TheSpaceCuber commented
Added return statements 

https://stackoverflow.com/questions/37726863/nodejs-difference-between-res-json-and-return-res-json

2022-10-02 07:01 UTC, ongweisheng requested changes
No issues other than the 1 comment and await @hiongkaihan review for merging

2022-10-02 07:01 UTC, ongweisheng commented on matching-service/controllers/matchController.js
> +            res.status(200).json({
Add return statement for this res.status(200).json()

2022-10-02 13:21 UTC, hiongkaihan commented
LGTM

2022-10-02 13:22 UTC, hiongkaihan approved these changes
LGTM

2022-10-02 13:24 UTC, ongweisheng approved these changes
LGTM!

2022-10-02 13:24 UTC, merged