Fix matching-service frontend bugs
CS3219-AY2223S1/cs3219-project-ay2223s1-g59 pull request #36
Opened 2022-10-05 14:35 UTC by ongweisheng

- Fix able to not select difficulty and find match (Must select difficulty now before finding match)
- Fix unable to end interview if the other user ended the interview first (Able to end interview and go back to home page even if the other user ends the interview first)

2022-10-05 14:48 UTC, TheSpaceCuber commented on frontend/src/components/HomePage.js
> +        }
Alternatively default difficulty can be easy, but this works too.

2022-10-05 16:10 UTC, hiongkaihan commented on frontend/src/components/InterviewPage.js
> +                            setQuestionTitle("")
LGTM
However not sure if we should standardize using async/await vs using promises

2022-10-06 08:04 UTC, Herrekt requested changes
Tested matching however after the timer runs out. I was not able to cancel matchmaking when "Unable to find match" comes out and return to the question difficulty selection menu. It just stays stuck on the menu although I clicked and confirm cancel find match.
In console, it returns: 
"
CS2106 waiting for match, timer at 31 seconds
No interview found for: CS2106
Error 500: Unable to delete match request in DB as no match entry found for user: CS2106
"

2022-10-06 09:57 UTC, Herrekt approved these changes
LGTM!

2022-10-06 09:57 UTC, merged