Run multiple node servers in one terminal and one command with concurrently
CS3219-AY2223S1/cs3219-project-ay2223s1-g59 pull request #53
Opened 2022-10-10 12:43 UTC by TheSpaceCuber

* Updated README with instructions on how to use it. Not a dependency since can install globally.
* Since all node servers are in the same terminal, require unique print statements for index.js.

2022-10-10 13:22 UTC, ongweisheng requested changes

2022-10-10 13:22 UTC, ongweisheng commented on matching-service/index.js
>      uri = process.env.DB_DOCKER_URI
Make equal changes to all the other service, NODE_ENV == "production" instead of ENV == "PROD"

2022-10-11 05:56 UTC, ongweisheng approved these changes
LGTM!

2022-10-12 18:27 UTC, hiongkaihan commented on README.md
> +SECRET=
Maybe can add a note/comment under the env example like "add DB_CLOUD_URI if you want to connect to mongodb cloud....SECRET if you want to set the secret variable..."

or

add `<Placeholder>` for DB_CLOUD_URI and SECRET 
eg.  SECRET=`<secret phrase for token encryption>` DB_CLOUD_URI=`<MongoDB cloud connection string>`

2022-10-13 17:53 UTC, hiongkaihan approved these changes
LGTM

2022-10-13 17:54 UTC, merged